### PR TITLE
Remove subject common name parsing

### LINKED ISSUE #167: rustls-webpki returns an error when parsing DNS names from a certificate generated using cfssl
## Summary

`rustls-webpki`'s `EndEntityCert::dns_names` iterator returns an error when called on a certificate generated using [`cloudflare/cfssl`](https://github.com/cloudflare/cfssl) and converted from PEM to DER using the `openssl` command-line tool. Meanwhile, Go's `crypto/x509` package successfully parses the DNS names. 

Both `crypto/x509` and `rustls-webpki` do successfully validate these certificates.

## Details

- **`rustls-webpki` versions**: This issue occurs with both v0.101.4 and v0.102.0-alpha-1 of `rustls-webpki`.
- **Presence or lack of a common name**: This issue occurs when a certificate is generated with or without a common name field, although v0.102.0-alpha.1 emits a different error when there is no common name (`TrailingData(CommonNameOuter)` rather than `BadDer`).

## Reproduction

I've written a reproduction for this issue in https://github.com/hawkw/rustls-webpki-repro. The reproduction includes:

- [a Rust program](https://github.com/hawkw/rustls-webpki-repro/blob/main/src/main.rs) that attempts to read the cert's DNS names using `rustls-webpki` v0.101.4 and v0.102.0-alpha.1
- [a Go program](https://github.com/hawkw/rustls-webpki-repro/blob/main/main.go) that does the same thing using the Go `crypto/x509` package
- [the certificates](https://github.com/hawkw/rustls-webpki-repro/tree/main/testdata) themselves
- [a Bash script](https://github.com/hawkw/rustls-webpki-repro/blob/main/gen-certs.sh) for generating the certificates.

I'm not really a TLS or ASN.1 expert, so please let me know if there's any additional information I can provide. Thanks!

### Go program output

<details>

<summary>The Go program included in the repro emits the following output:</summary>

```console
$ go run repro
=== Path: testdata/no-cn-test-ca1/crt.der===

--- go crypto/x509 ---

Verified valid for no-cn.test.com
Subject:
NotBefore: 2023-09-06 17:21:00 +0000 UTC
NotAfter: 2033-09-03 17:21:00 +0000 UTC

printing DNS names...
DNSNames[0]: no-cn.test.com


=== Path: testdata/cn-test-ca1/crt.der===

--- go crypto/x509 ---

Verified valid for cn.test.com
Subject: CN=cn.test.com
NotBefore: 2023-09-06 17:21:00 +0000 UTC
NotAfter: 2033-09-03 17:21:00 +0000 UTC

printing DNS names...
DNSNames[0]: cn.test.com

```

</details>

### Rust repro output

<details>
<summary>The Rust repro emits the following output:</summary>

```console
$ cargo run
   Compiling rustls-webpki-repro v0.1.0 (/home/eliza/Code/rustls-webpki-repro)
    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
     Running `target/debug/rustls-webpki-repro`
=== Path: testdata/no-cn-test-ca1/crt.der ===

--- rustls-webpki v0.101.4 ---

Verified valid for no-cn.test.com
printing DNS names...
Error: BadDer

--- rustls-webpki v0.102.0-alpha.1 ---

Verified valid for no-cn.test.com
printing DNS names...
Error: TrailingData(CommonNameOuter)

=== Path: testdata/cn-test-ca1/crt.der ===

--- rustls-webpki v0.101.4 ---

Verified valid for cn.test.com
printing DNS names...
Error: BadDer

--- rustls-webpki v0.102.0-alpha.1 ---

Verified valid for cn.test.com
printing DNS names...
Error: BadDer

```

</details>

### Expected output

<details>
<summary>I would expect the Rust program to instead output something more similar to the Go program, like:</summary>

```console
$ cargo run
   Compiling rustls-webpki-repro v0.1.0 (/home/eliza/Code/rustls-webpki-repro)
    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
     Running `target/debug/rustls-webpki-repro`
=== Path: testdata/no-cn-test-ca1/crt.der ===

--- rustls-webpki v0.101.4 ---

Verified valid for no-cn.test.com
printing DNS names...
dns_names[0]: no-cn.test.com

--- rustls-webpki v0.102.0-alpha.1 ---

Verified valid for no-cn.test.com
printing DNS names...
dns_names[0]: no-cn.test.com

=== Path: testdata/cn-test-ca1/crt.der ===

--- rustls-webpki v0.101.4 ---

Verified valid for cn.test.com
printing DNS names...
dns_names[0]: cn.test.com

--- rustls-webpki v0.102.0-alpha.1 ---

Verified valid for cn.test.com
printing DNS names...
dns_names[0]: cn.test.com
```

</details>

### PR DESCRIPTION
**Pull request by hawkw**
Currently, `rustls-webpki` fails to parse common names names from certificates where the subject common name is not a `UTF8String`, or a `SEQUENCE` containing an empty `SET`. This is incorrect, as some spec-compliant encoders may emit `PrintableString` rather than `UTF8String`, and may represent an empty subject common name as an empty `SEQUENCE`, rather than a `SEQUENCE` of empty `SET`. This results in issues while iterating over the subject alternate names of such a certificate, as described in rustls/webpki#167.

Rather than changing the common name parsing to support such cases, the simplest solution to these issues is to remove common name parsing entirely. As explained by @cpu in https://github.com/rustls/webpki/issues/167#issuecomment-1708981298:

> For the purpose of certificate validation we only rely on SANs. The common name handling code is only used for verifying name constraints, and for the name iteration code that you found the bug with. For the former, if we assume the webpki profile the subj. CN must be present as a SAN, so validating the SANs vs the constraints seems sufficient (?). For the latter, it seems potentially confusing to return a name from the CN that doesn't get used for validation (though again, the webpki profile would require that it matches a SAN value).

Therefore, this branch does the following:
- Introduce tests for iterating over the DNS names in certificates where the CN is a `PrintableString` (a53c3eec47fcf927c095bc1fbfd42901b1848f30) and where the CN is an empty `SEQUENCE` (c075316f742d1d554ae7e0f9f05b4325e6642676),
- Remove the existing tests for name constraints involving CNs which are not also present in the SANs, since the webpki profile requires the CN to also be a SAN (7d3107585e71f155739f94ce198659021c44559a)
- Remove the common name parsing from `rustls-webpki` entirely (ac1740c45b8c189192ae756e42d0fa13a52f687d and 429a31618eec82a42baba3b68b6fc41d5434a5da)

Fixes #167

### CODE REVIEW

File: tests/integration.rs [hunk 1]
```diff
@@ -262,117 +262,164 @@ fn time_constructor() {
...
+            let der = cert
+                .serialize_der_with_signer(&issuer)
+                .expect("failed to serialize signed ee cert (this is a test bug)");
+            der
+        };
+
+        expect_cert_dns_names(&ee_cert_derd, &[DNS_NAME]);
+    }
+
+    fn mk_issuer(alg: &'static rcgen::SignatureAlgorithm) -> rcgen::Certificate {
```
Comment (cpu) [inline tests/integration.rs:395]: This helper is pretty close to the `verify_cert.rs` helper `make_issuer`. 

Is there a convenient way to allow both `tests/integration.rs` and `src/verify_cert.rs`'s unit tests to share the same rcgen helpers?

File: src/subject_name/verify.rs [hunk 2]
```diff
@@ -31,29 +31,25 @@ pub(crate) fn verify_cert_dns_name(
...
-    .find_map(|result| {
-        let name = match result {
-            Ok(name) => name,
-            Err(err) => return Some(Err(err)),
-        };
+    NameIterator::new(Some(cert.subject), cert.subject_alt_name)
+        .find_map(|result| {
+            let name = match result {
+                Ok(name) => name,
+                Err(err) => return Some(Err(err)),
```
Comment (hawkw) [inline src/subject_name/verify.rs:38]: Not totally sure what to do about the Codecov warning on this line (and on the one later in this method) --- it's saying this line was "added", but that's only because the change to remove the `SubjectCommonNameContents` from the call to `NameIterator::new` was removed, resulting in `rustfmt` reformatting all this code. This exact match statement was there before, and (presumably) also not covered by tests?

File: tests/integration.rs [hunk 3]
```diff
@@ -374,13 +375,21 @@ mod subject_alt_names {
...
+        expect_cert_dns_names(&ee_cert_der, &[DNS_NAME]);
+    }
+
+    // This test reproduces https://github.com/rustls/webpki/issues/167 --- an
+    // end-entity cert where the common name is an empty SEQUENCE.
+    #[test]
+    pub fn empty_sequence_common_name() {
+        // handcrafted cert DER produced using `ascii2der`, since `rcgen` is
+        // unwilling to generate this particular weird cert.
+        let ee_cert_der = include_bytes!("misc/empty_sequence_common_name.der");
```
Comment (cpu) [inline tests/integration.rs:391]: For some of the other hand-crafted certs I've added recently that were produced with `ascii2der` I've also checked in the `.txt` representation that generated the DER, e.g.: [crl.idp.explicit.false.bool.der.txt](https://github.com/rustls/webpki/blob/main/tests/crls/crl.idp.explicit.false.bool.der.txt).

It isn't something we're doing today but eventually it would be nice to have CI check that the regenerating the `.der` from the `.txt` produces no diff. It also makes it easier for a reviewer to understand what the `.der` is doing when a new test case is added.

File: src/der.rs [hunk 4]
```diff
@@ -62,9 +62,9 @@ pub(crate) enum Tag {
     OctetString = 0x04,
     OID = 0x06,
     Enum = 0x0A,
-    UTF8String = 0x0C,
+    // UTF8String = 0x0C,
```
Comment (cpu) [inline src/der.rs:65]: I think since this enum already has gaps in the the tag value space it's OK to delete the unused entries rather than leave them commented out. WDYT?

File: src/subject_name/verify.rs (hunk 2 above)
Comment (cpu) [reply src/subject_name/verify.rs:38]: We're not super nit-picky about this kind of codecov finding IME. I think you make a reasonable case for why it isn't important to address in this branch.

**Review by cpu — COMMENTED** [review]
Here's some initial feedback. Thanks again for running with this :tada: It will be really nice to put another nail in the subject common name coffin.

File: tests/integration.rs (hunk 3 above)
Comment (hawkw) [reply tests/integration.rs:391]: I'm happy to check the text file in as well!

File: tests/integration.rs (hunk 1 above)
Comment (hawkw) [reply tests/integration.rs:395]: Hmm. Unfortunately, I think the only way to share the helper between tests inside the library and integration tests is to make it a public API, which we probably don't want to do. Alternatively, I could move these tests out of integration and into `src/verify_cert.rs`, but they felt more like integration tests because they just interact with public APIs and I wanted to be able to use the existing `expect_cert_dns_names` helper in the new tests. Would you prefer them in `verify_cert.rs`? I'm happy to move them.

File: src/der.rs (hunk 4 above)
Comment (hawkw) [reply src/der.rs:65]: Cool, I wasn't sure what would be preferred. I can remove the unused tag variants.

File: tests/integration.rs (hunk 1 above)
Comment (cpu) [reply tests/integration.rs:395]: > Hmm. Unfortunately, I think the only way to share the helper between tests inside the library and integration tests is to make it a public API, which we probably don't want to do.

Blech, yeah that's no good. 

>  Alternatively, I could move these tests out of integration and into src/verify_cert.rs, but they felt more like integration tests because they just interact with public APIs and I wanted to be able to use the existing expect_cert_dns_names helper in the new tests. Would you prefer them in verify_cert.rs? I'm happy to move them.

I think `src/end_entity.rs` might be a better fit since the unit tests are specific to the `EndEntity::dns_names` fn and not related to certificate validation, but that shifts the problem to how to have `src/end_entity.rs` and `src/verify_cert.rs` share helpers. :thinking: However, maybe that's more more tractable there since they're both crate-internal locations?

I don't have a super strong preference.

@djc @ctz Do you have thoughts? Another idea is to leave the duplication in and consider upstream work in `rcgen` that could reduce the need for the helper boilerplate. I have some ideas there but it will take some time to implement.

Comment (hawkw) [reply tests/integration.rs:395]: We can more easily share test helpers within the crate. I think moving these tests to `end_entity` and making a shared crate-private `test_util` module would be the best solution here, probably.

File: src/verify_cert.rs [hunk 5]
```diff
@@ -1113,58 +1113,4 @@ mod tests {
                 .unwrap(),
         )
     }
-
```
Comment (djc) [inline src/verify_cert.rs]: FYI, we usually rebase-merge instead of squashing so we can retain more easily reviewable atomic commits, but I don't love the commit history here. This is moving code that was just introduced in the previous commit to a different place, and splicing it into a bunch of tests that's moved into a module in the same commit.

Ideally we'd have the first commit move the tests into the module, and the second commit adding the new test.

File: tests/integration.rs [hunk 6]
```diff
@@ -352,10 +352,9 @@ mod subject_alt_names {
         assert!(names.collect::<Vec<_>>().is_empty());
     }
 
-    // This test reproduces (part of)
-    // https://github.com/rustls/webpki/issues/167 --- an end-entity cert where
-    // the common name is a `PrintableString` rather than a `UTF8String` cannot
-    // iterate over its subject alternative names.
+    // This test reproduces https://github.com/rustls/webpki/issues/167 --- an
```
Comment (djc) [inline tests/integration.rs]: These changes should probably get squashed into the commit introducing the new test.

File: src/subject_name/verify.rs [hunk 7]
```diff
@@ -345,20 +345,9 @@ impl<'a> Iterator for NameIterator<'a> {
...
-            return match common_name(subject_common_name) {
-                Ok(Some(cn)) => Some(Ok(GeneralName::DnsName(cn))),
-                Ok(None) => None,
-                // All the iterator fields should be `None` at this point
-                Err(err) => Some(Err(err)),
-            };
-        }
-
-        None
+        self.subject_directory_name
```
Comment (djc) [inline src/subject_name/verify.rs:321]: I think this is just reformulating the `if let Some()` that was there before, right? I wrote that, and I still feel like it was easier to comprehend than this combinator-based spelling.

(If we want to change it, I'd prefer to have that split in a separate commit from the logic removing the `self.subject_common_name` handling.)

File: tests/misc/empty_sequence_common_name.der.txt [hunk 8]
```diff
@@ -0,0 +1,104 @@
+SEQUENCE {
```
Comment (djc) [inline tests/misc/empty_sequence_common_name.der.txt:1]: This should go in the commit that introduces the test.

File: src/der.rs [hunk 9]
```diff
@@ -62,9 +62,7 @@ pub(crate) enum Tag {
     OctetString = 0x04,
     OID = 0x06,
     Enum = 0x0A,
-    // UTF8String = 0x0C,
```
Comment (djc) [inline src/der.rs]: These should be squashed in the earlier commit that commented them out.

**Review by djc — COMMENTED** [review]
Some thoughts on how to make the commit history a bit cleaner...

File: src/verify_cert.rs (hunk 5 above)
Comment (hawkw) [reply src/verify_cert.rs]: I'm happy to squash commits however you like. I'm used to working in repos where PRs are squash merged, sorry!

Comment (djc) [reply src/verify_cert.rs]: No problem, I'm aware that the tokio repos usually squash, just making it explicit -- hopefully it won't be too painful.

Comment (hawkw) [reply src/verify_cert.rs]: Okay, I've rewritten the history into three commits: one that adds the new tests, one that removes the tests for CNs in name constraints, and one that removes the actual common name parsing. I've also addressed your feedback on the change to `NameIterator`. Let me know what you think --- I'm happy to make additional changes to the Git history if there's anything else you'd like changed.

**Review by djc — APPROVED** [review]
Yup, this is great! I'd probably have kept the extraction/move of test utils in a separate commit, but that doesn't matter as much.

BTW, the content of the changes looks great, some nice simplification here.

**Comment by hawkw** [comment]
> I'd probably have kept the extraction/move of test utils in a separate commit, but that doesn't matter as much.

Ah, yeah, probably should have pulled that out, my bad! Oh well --- not sure if it can be easily changed now. 

Also, I had to force-push again after noticing a clippy lint on an earlier commit, so if you don't mind, it looks like CI will need to be re-approved.

File: tests/integration.rs (hunk 1 above)
Comment (cpu) [reply tests/integration.rs]: >  making a shared crate-private test_util module would be the best solution here, probably.

SGTM. Let's roll with that and resolve this conversation.

**Review by cpu — APPROVED** [review]
Nice work!

**Comment by cpu** [comment]
I'm going to leave this unmerged overnight to give ctz a chance to do a review in case he's interested. If it isn't merged or reviewed by the time I log back on east-coast morning time tomorrow. I'll go ahead and merge.

**Comment by hawkw** [comment]
@cpu Sounds good to me! We would love to be able to get a release with this fixed, of course. But, since it looks you all are in the middle of getting v0.102.0 ready , we can definitely take a Git dependency in the meantime. 

Thanks so much for all your guidance on figuring out the issue and how to fix it, I really appreciate it!

File: tests/integration.rs (hunk 1 above)
Comment (ctz) [reply tests/integration.rs]: I think for sharing test-only code between unit and integration tests, it's reasonable to put that code in the crate, and then reuse it from integration tests by

```rust
#[path = "../src/test_util.rs"]
mod test_util;
```

That means the code in `test_util.rs` is more restricted than usual (it can't reference crate internals, etc.) But for helpers and test fixtures that should be OK.

**Review by ctz — APPROVED** [review]
Looks great, thanks!

**Comment by djc** [comment]
@hawkw if you want to do a backport to 0.101.x we'd be happy to review and merge that, but other than that, taking on a rustls alpha release might make sense? Will require some other changes though (but would be great to have early feedback on those anyway). Backport probably won't be completely trivial, this code changed a bunch since 0.101.

**Comment by cpu** [comment]
I'm working on a 0.101.x release branch, I can take a look at folding this in.

**Comment by cpu** [comment]
> I'm working on a 0.101.x release branch, I can take a look at folding this in.

It wasn't too bad to backport :+1: https://github.com/rustls/webpki/pull/170

**Comment by hawkw** [comment]
> > I'm working on a 0.101.x release branch, I can take a look at folding this in.
> 
> It wasn't too bad to backport 👍 #170

Thank you, that's wonderful! I would've been fine with a Git dep on the alpha, so thank you for going out of your way to do that!
