### PR TITLE
fix no-std support

### LINKED ISSUE #143: webpki compiled without default features and the alloc feature enabled depends on std
Steps to reproduce
``` console
$ cargo b --no-default-features --features alloc
```
yields errors when building `src/crl.rs` due to two reasons
1. `Vec` is used without importing it from `alloc` first
2. [`HashMap`](https://github.com/rustls/webpki/blob/aa818ab796dd873edd897b3174f2b5590bea19d5/src/crl.rs#L22) is imported but that's defined in the `std` crate

Fixing (1) is easy. The easiest fix for (2) is using `BTreeMap` but that has different [performance costs](https://doc.rust-lang.org/std/collections/index.html#maps)

### LINKED ISSUE #144: webpki compiled without default features and the alloc feature enabled builds the optional ring feature
but shouldn't

Steps to reproduce
``` console
$ cargo b --target x86_64-unknown-none --no-default-features --features alloc
   Compiling ring v0.16.20
error[E0425]: cannot find function `fill_impl` in this scope
```

this line in the Cargo.toml
https://github.com/rustls/webpki/blob/aa818ab796dd873edd897b3174f2b5590bea19d5/Cargo.toml#L68

is bringing in the ring dependency when the `alloc` feature is enabled. probably the intention what to enable ring's alloc feature *iff* the ring feature is also enabled. in that case, the Cargo.toml should use [`ring?/alloc`](https://doc.rust-lang.org/cargo/reference/features.html#dependency-features)

### PR DESCRIPTION
**Pull request by japaric**
this PR
- makes the `alloc` feature not pull in the optional `ring` dependency
- fixes `cargo build --no-default-features --features alloc`
- adds a CI check to prevent no-std support breaking in the future

fixes #143 
fixes #144

### CODE REVIEW

**Review by djc — APPROVED** [review]

File: src/crl.rs [hunk 1]
```diff
@@ -19,7 +19,9 @@ use crate::x509::{remember_extension, set_extension_once, DistributionPointName,
 use crate::{Error, SignatureVerificationAlgorithm, Time};
 
 #[cfg(feature = "alloc")]
-use std::collections::HashMap;
+use alloc::collections::BTreeMap as Map;
```
Comment (djc) [inline src/crl.rs:22]: As is, there doesn't seem to be much utility in renaming `BTreeMap` to `Map`.

**Review by cpu — APPROVED** [review]
Thanks!

I think the different performance characteristics of the `BTreeMap` vs `HashMap` are probably not significant enough in this use-case to merit trying to do more complicated abstraction to allow switching between the two based on features.

Running `cargo bench` on tip of `main` and on this branch shows that the `BTreeMap`-based owned representation is faster for the initial parsing of a chonky CRL and only a bit slower for lookups. I think it's a reasonable trade-off.

HashMap:
```
test bench_parse_owned_crl_large      ... bench: 517,452,454 ns/iter (+/- 98,860,890)
test bench_parse_owned_crl_medium     ... bench: 176,374,780 ns/iter (+/- 32,024,576)
test bench_parse_owned_crl_small      ... bench:     186,129 ns/iter (+/- 7,450)
test bench_search_owned_crl_large     ... bench:           9 ns/iter (+/- 3)
test bench_search_owned_crl_medium    ... bench:           9 ns/iter (+/- 3)
test bench_search_owned_crl_small     ... bench:          10 ns/iter (+/- 1)
```

BTreeMap:
```
test bench_parse_owned_crl_large      ... bench: 296,112,924 ns/iter (+/- 37,342,479)
test bench_parse_owned_crl_medium     ... bench:  89,594,215 ns/iter (+/- 13,807,766)
test bench_parse_owned_crl_small      ... bench:     175,042 ns/iter (+/- 19,676)
test bench_search_owned_crl_large     ... bench:          63 ns/iter (+/- 16)
test bench_search_owned_crl_medium    ... bench:          69 ns/iter (+/- 13)
test bench_search_owned_crl_small     ... bench:          50 ns/iter (+/- 2)
```

File: src/crl.rs (hunk 1 above)
Comment (japaric) [reply src/crl.rs]: I have undone the rename

**Comment by cpu** [comment]
@ctz Thoughts? Ready for merge queue?

**Comment by cpu** [comment]
I'm going to bypass the merge queue for this one while the dependency fetching flake is happening. It keeps getting bounced from the queue :slot_machine:
